import asyncio
from datetime import datetime
import requests
import os
import django

# Configurar Django
#os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
#django.setup()

# Ahora puedes importar y trabajar con tus modelos
#from cryptobrecha.models import Banco, Usuario

countries= ["PE"]

print("countries ",type(countries))

#"classifies": [
#                "mass",
#                "profession"
#            ]


muestra={
    "code": "000000",
    "message": None,
    "messageDetail": None,
    "data": [
        {
            "adv": {
                "advNo": "11407067633785008128",
                "classify": "mass",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.003",
                "initAmount": None,
                "surplusAmount": "332.31",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "1500.00",
                "minSingleTransAmount": "50.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "AirTM",
                        "iconUrlColor": None,
                        "tradeMethodName": "AirTM",
                        "tradeMethodShortName": "AirTM",
                        "tradeMethodBgColor": "#1783FA"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "332.14",
                "minSingleTransQuantity": "49.85",
                "maxSingleTransQuantity": "1495.51",
                "dynamicMaxSingleTransQuantity": "331.15",
                "tradableQuantity": "331.15",
                "commissionRate": "0.00350000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s82f840c67bff3e1ea46c683540285018",
                "realName": None,
                "nickName": "Torre",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 92,
                "monthFinishRate": 1.000,
                "positiveRate": 0.99430199,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "user",
                "tagIconUrls": [],
                "userGrade": 2,
                "userIdentity": "",
                "proMerchant": None,
                "badges": None,
                "isBlocked": None,
                "activeTimeInSecond": 1602
            }
        },
        {
            "adv": {
                "advNo": "11552978956869615616",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.008",
                "initAmount": None,
                "surplusAmount": "855.94",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "2016.00",
                "minSingleTransAmount": "50.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Zinli",
                        "iconUrlColor": None,
                        "tradeMethodName": "Zinli",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#5A37B4"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "860.37",
                "minSingleTransQuantity": "49.60",
                "maxSingleTransQuantity": "2000.00",
                "dynamicMaxSingleTransQuantity": "853.55",
                "tradableQuantity": "853.55",
                "commissionRate": "0.00280000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s3264120bf5d738789d2a412bcc095220",
                "realName": None,
                "nickName": "TRANDING-JCN",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 188,
                "monthFinishRate": 0.913,
                "positiveRate": 0.99714828,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 615
            }
        },
        {
            "adv": {
                "advNo": "12585090827941474304",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.009",
                "initAmount": None,
                "surplusAmount": "277.63",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "15000.00",
                "minSingleTransAmount": "90.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Mony",
                        "iconUrlColor": None,
                        "tradeMethodName": "Mony",
                        "tradeMethodShortName": "Mony",
                        "tradeMethodBgColor": "#0D519D"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Zinli",
                        "iconUrlColor": None,
                        "tradeMethodName": "Zinli",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#5A37B4"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BanescoPanama",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banesco Panama",
                        "tradeMethodShortName": "Banesco Panama",
                        "tradeMethodBgColor": "#00794F"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "MercantilBankPanama",
                        "iconUrlColor": None,
                        "tradeMethodName": "Mercantil Bank Panama",
                        "tradeMethodShortName": "Mercantil Bank Panama",
                        "tradeMethodBgColor": "#013091"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "279.34",
                "minSingleTransQuantity": "89.19",
                "maxSingleTransQuantity": "14866.20",
                "dynamicMaxSingleTransQuantity": "276.85",
                "tradableQuantity": "276.85",
                "commissionRate": "0.00280000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "sab2e9371e1243a45ba849fec020f46bd",
                "realName": None,
                "nickName": "DIGITAL---SERVICES",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 284,
                "monthFinishRate": 0.973,
                "positiveRate": 0.99811241,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 1151
            }
        },
        {
            "adv": {
                "advNo": "11346473915409207296",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.013",
                "initAmount": None,
                "surplusAmount": "100.00",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "4000.00",
                "minSingleTransAmount": "100.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "AirTM",
                        "iconUrlColor": None,
                        "tradeMethodName": "AirTM",
                        "tradeMethodShortName": "AirTM",
                        "tradeMethodBgColor": "#1783FA"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "101.01",
                "minSingleTransQuantity": "98.71",
                "maxSingleTransQuantity": "3948.66",
                "dynamicMaxSingleTransQuantity": "99.72",
                "tradableQuantity": "99.72",
                "commissionRate": "0.00280000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "sd5a228b5b2df323ebf840d45da5ee8a1",
                "realName": None,
                "nickName": "MEJOR CAMBIO",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 1032,
                "monthFinishRate": 0.947,
                "positiveRate": 0.98183804,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "BLOCK_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Block"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 646
            }
        },
        {
            "adv": {
                "advNo": "11446956378274533376",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.014",
                "initAmount": None,
                "surplusAmount": "135.31",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "500.00",
                "minSingleTransAmount": "10.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Zinli",
                        "iconUrlColor": None,
                        "tradeMethodName": "Zinli",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#5A37B4"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "136.82",
                "minSingleTransQuantity": "9.86",
                "maxSingleTransQuantity": "493.09",
                "dynamicMaxSingleTransQuantity": "134.93",
                "tradableQuantity": "134.93",
                "commissionRate": "0.00280000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s270a3aa40e663c1c942a13cf55b27699",
                "realName": None,
                "nickName": "Mlaura2020",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 888,
                "monthFinishRate": 0.995,
                "positiveRate": 0.99502415,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 5077
            }
        },
        {
            "adv": {
                "advNo": "11472415122562256896",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.015",
                "initAmount": None,
                "surplusAmount": "301.21",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "500.00",
                "minSingleTransAmount": "10.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "WallyTech",
                        "iconUrlColor": None,
                        "tradeMethodName": "Wally Tech",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#EE9D25"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "304.87",
                "minSingleTransQuantity": "9.85",
                "maxSingleTransQuantity": "492.61",
                "dynamicMaxSingleTransQuantity": "300.36",
                "tradableQuantity": "300.36",
                "commissionRate": "0.00280000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s3c0230fdd12839659e151cc43dbcb2d5",
                "realName": None,
                "nickName": "Adler",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 932,
                "monthFinishRate": 0.987,
                "positiveRate": 0.99892093,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 2610
            }
        },
        {
            "adv": {
                "advNo": "12576244115404701696",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.017",
                "initAmount": None,
                "surplusAmount": "1578.80",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "5000.00",
                "minSingleTransAmount": "15.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BancoGeneralPanama",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banco General Panama",
                        "tradeMethodShortName": "Banco General Panama",
                        "tradeMethodBgColor": "#004B9B"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Towerbank",
                        "iconUrlColor": None,
                        "tradeMethodName": "Towerbank",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#183785"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BancoNacionalPanama",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banco Nacional de Panamá",
                        "tradeMethodShortName": "Banco Nacional de Panamá",
                        "tradeMethodBgColor": "#0553AD"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BACCredomatic",
                        "iconUrlColor": None,
                        "tradeMethodName": "BAC Credomatic",
                        "tradeMethodShortName": "BAC Credomatic",
                        "tradeMethodBgColor": "#C8102F"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "TransferenciaACH",
                        "iconUrlColor": None,
                        "tradeMethodName": "Transferencia ACH (Panamá)",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#DAB764"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "1601.71",
                "minSingleTransQuantity": "14.74",
                "maxSingleTransQuantity": "4916.42",
                "dynamicMaxSingleTransQuantity": "1574.94",
                "tradableQuantity": "1574.94",
                "commissionRate": "0.00245000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "sa0d7af6dcc193d609790dded58d8974b",
                "realName": None,
                "nickName": "kctrading",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 1775,
                "monthFinishRate": 0.999,
                "positiveRate": 1.00000000,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 2
            }
        },
        {
            "adv": {
                "advNo": "12583856430970892288",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.017",
                "initAmount": None,
                "surplusAmount": "544.63",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "5000000.00",
                "minSingleTransAmount": "50.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "CreditBankofPeru",
                        "iconUrlColor": None,
                        "tradeMethodName": "Credit Bank of Peru",
                        "tradeMethodShortName": "BCP",
                        "tradeMethodBgColor": "#002A8D"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BancoDeCredito",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banco de Credito",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#FF7B00"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Interbank",
                        "iconUrlColor": None,
                        "tradeMethodName": "Interbank",
                        "tradeMethodShortName": "Interbank",
                        "tradeMethodBgColor": "#00BB31"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BBVABank",
                        "iconUrlColor": None,
                        "tradeMethodName": "BBVA",
                        "tradeMethodShortName": "BBVA",
                        "tradeMethodBgColor": "#283572"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "552.53",
                "minSingleTransQuantity": "49.16",
                "maxSingleTransQuantity": "4916420.84",
                "dynamicMaxSingleTransQuantity": "543.29",
                "tradableQuantity": "543.29",
                "commissionRate": "0.00245000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "sa850d5a14e0239f2b958d3495b105e78",
                "realName": None,
                "nickName": "CRYPTO--INFINITY",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 1567,
                "monthFinishRate": 1.000,
                "positiveRate": 1.00000000,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 375
            }
        },
        {
            "adv": {
                "advNo": "12558303474210222080",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.018",
                "initAmount": None,
                "surplusAmount": "11466.05",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "10000.00",
                "minSingleTransAmount": "100.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Interbank",
                        "iconUrlColor": None,
                        "tradeMethodName": "Interbank",
                        "tradeMethodShortName": "Interbank",
                        "tradeMethodBgColor": "#00BB31"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BancoDeCredito",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banco de Credito",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#FF7B00"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "CreditBankofPeru",
                        "iconUrlColor": None,
                        "tradeMethodName": "Credit Bank of Peru",
                        "tradeMethodShortName": "BCP",
                        "tradeMethodBgColor": "#002A8D"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "10000.00",
                "minSingleTransQuantity": "98.23",
                "maxSingleTransQuantity": "9823.18",
                "dynamicMaxSingleTransQuantity": "9823.18",
                "tradableQuantity": "11438.02",
                "commissionRate": "0.00245000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s83bfc5c436283c08aa45dc5e4494b2c6",
                "realName": None,
                "nickName": "PLUSDEAL",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 660,
                "monthFinishRate": 0.997,
                "positiveRate": 0.99820282,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 164
            }
        },
        {
            "adv": {
                "advNo": "11549265916272898048",
                "classify": "profession",
                "tradeType": "SELL",
                "asset": "USDT",
                "fiatUnit": "USD",
                "advStatus": None,
                "priceType": None,
                "priceFloatingRatio": None,
                "rateFloatingRatio": None,
                "currencyRate": None,
                "price": "1.018",
                "initAmount": None,
                "surplusAmount": "21107.08",
                "amountAfterEditing": None,
                "maxSingleTransAmount": "10000.00",
                "minSingleTransAmount": "100.00",
                "buyerKycLimit": None,
                "buyerRegDaysLimit": None,
                "buyerBtcPositionLimit": None,
                "remarks": None,
                "autoReplyMsg": "",
                "payTimeLimit": 15,
                "tradeMethods": [
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "Interbank",
                        "iconUrlColor": None,
                        "tradeMethodName": "Interbank",
                        "tradeMethodShortName": "Interbank",
                        "tradeMethodBgColor": "#00BB31"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "CreditBankofPeru",
                        "iconUrlColor": None,
                        "tradeMethodName": "Credit Bank of Peru",
                        "tradeMethodShortName": "BCP",
                        "tradeMethodBgColor": "#002A8D"
                    },
                    {
                        "payId": None,
                        "payMethodId": "",
                        "payType": None,
                        "payAccount": None,
                        "payBank": None,
                        "paySubBank": None,
                        "identifier": "BancoDeCredito",
                        "iconUrlColor": None,
                        "tradeMethodName": "Banco de Credito",
                        "tradeMethodShortName": None,
                        "tradeMethodBgColor": "#FF7B00"
                    }
                ],
                "userTradeCountFilterTime": None,
                "userBuyTradeCountMin": None,
                "userBuyTradeCountMax": None,
                "userSellTradeCountMin": None,
                "userSellTradeCountMax": None,
                "userAllTradeCountMin": None,
                "userAllTradeCountMax": None,
                "userTradeCompleteRateFilterTime": None,
                "userTradeCompleteCountMin": None,
                "userTradeCompleteRateMin": None,
                "userTradeVolumeFilterTime": None,
                "userTradeType": None,
                "userTradeVolumeMin": None,
                "userTradeVolumeMax": None,
                "userTradeVolumeAsset": None,
                "createTime": None,
                "advUpdateTime": None,
                "fiatVo": None,
                "assetVo": None,
                "advVisibleRet": None,
                "takerAdditionalKycRequired": 0,
                "assetLogo": None,
                "assetScale": 2,
                "fiatScale": 2,
                "priceScale": 3,
                "fiatSymbol": "$",
                "isTradable": True,
                "dynamicMaxSingleTransAmount": "10000.00",
                "minSingleTransQuantity": "98.23",
                "maxSingleTransQuantity": "9823.18",
                "dynamicMaxSingleTransQuantity": "9823.18",
                "tradableQuantity": "21055.49",
                "commissionRate": "0.00245000",
                "takerCommissionRate": None,
                "tradeMethodCommissionRates": [],
                "launchCountry": None,
                "abnormalStatusList": None,
                "closeReason": None,
                "storeInformation": None,
                "allowTradeMerchant": None
            },
            "advertiser": {
                "userNo": "s3f26fd25a53c3b66a45ad3611be6b663",
                "realName": None,
                "nickName": "AEC_SPACE",
                "margin": None,
                "marginUnit": None,
                "orderCount": None,
                "monthOrderCount": 1292,
                "monthFinishRate": 0.998,
                "positiveRate": 0.99642715,
                "advConfirmTime": None,
                "email": None,
                "registrationTime": None,
                "mobile": None,
                "userType": "merchant",
                "tagIconUrls": [],
                "userGrade": 3,
                "userIdentity": "MASS_MERCHANT",
                "proMerchant": None,
                "badges": [
                    "Ordinary"
                ],
                "isBlocked": None,
                "activeTimeInSecond": 80
            }
        }
    ],
    "total": 40,
    "success": True
}


print("Muestra = ",muestra)

print("Type: ",type(muestra))